# Generated by Django 2.1.5 on 2019-01-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('symptoms', models.CharField(max_length=5000, null=True)),
                ('category', models.CharField(choices=[('Alcohol and drug misuse', 'Alcohol and drug misuse'), ('Blood and lymph', 'Blood and lymph'), ('Brain, nerves and spinal cord', 'Brain, nerves and spinal cord'), ('Cancer', 'Cancer'), ('Diabetes', 'Diabetes'), ('Ears, nose and throat', 'Ears, nose and throat'), ('Eyes', 'Eyes'), ('Glands', 'Glands'), ('Heart and blood vessels', 'Heart and blood vessels'), ('Immune system', 'Immune system'), ('Infections and poisoning', 'Infections and poisoning'), ('Injuries', 'Injuries'), ('Kidneys, bladder and prostate', 'Kidneys, bladder and prostate'), ('Lungs and airways', 'Lungs and airways'), ('Mental health', 'Mental health'), ('Mouth', 'Mouth'), ('Muscle, bone and joints', 'Muscle, bone and joints'), ('Nutritional', 'Nutritional'), ('Pregnancy and childbirth', 'Pregnancy and childbirth'), ('Sexual and reproductive', 'Sexual and reproductive'), ('Stomach, liver and gastrointestinal tract', 'Stomach, liver and gastrointestinal tract')], default='Other', max_length=99)),
            ],
        ),
    ]
