# Generated by Django 2.1.5 on 2019-02-06 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20190206_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
