# Generated by Django 2.1.5 on 2019-02-09 23:17

import catalogue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20190209_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=catalogue.models.name_media_file, validators=[django.core.validators.FileExtensionValidator(('jpeg', 'jpg', 'png', 'gif', 'mp3', 'mp4', 'mpeg'))]),
        ),
    ]
