# Generated by Django 2.1.5 on 2019-02-10 12:18

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20190209_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, default='media/default_case.png', null=True, upload_to=catalogue.models.name_file, verbose_name='Main Image'),
        ),
    ]
