# Generated by Django 2.1.5 on 2019-02-10 18:09

import catalogue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20190210_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='moderator_comments',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=catalogue.models.name_media_file, validators=[django.core.validators.FileExtensionValidator(('.jpeg', '.jpg', '.png', '.gif', '.mp3', '.pcm', '.wav', '.flac', '.wma', '.mp4', '.mpeg', '.avi', '.flv', '.wmv', '.mov', '.mkv'))]),
        ),
    ]
