# Generated by Django 2.1.5 on 2019-02-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20190210_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='moderator_comments',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
