# Generated by Django 2.1.5 on 2019-02-11 17:11

import catalogue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20190211_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=catalogue.models.name_media_file, validators=[django.core.validators.FileExtensionValidator(('jpeg', 'jpg', 'png', 'gif', 'mp3', 'pcm', 'wav', 'flac', 'wma', 'mp4', 'mpeg', 'avi', 'flv', 'wmv', 'mov', 'pdf', 'csv'))]),
        ),
    ]
