# Generated by Django 2.1.7 on 2019-08-15 16:30

import catalogue.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0016_auto_20190301_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquirer_name', models.CharField(max_length=254, verbose_name='Name')),
                ('enquirer_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmarked_case',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='case',
            old_name='patient_age',
            new_name='Conversation_Date',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='clinician_observations',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='case',
            name='contact_allowed',
        ),
        migrations.RemoveField(
            model_name='case',
            name='moderator_comments',
        ),
        migrations.AlterField(
            model_name='case',
            name='ethnicity',
            field=models.CharField(choices=[('Insert tuples here', 'Insert tuples here')], default='Z: Other Ethnic Groups - Not stated', max_length=99),
        ),
        migrations.AlterField(
            model_name='case',
            name='gender',
            field=models.CharField(choices=[('Insert new field here', 'Insert new field here')], default='9 - Not Specified', max_length=99),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.name_file, verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.CharField(default='Other', max_length=99),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Case'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
