# Generated by Django 2.1.7 on 2019-08-15 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20190815_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Conversation_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
