# Generated by Django 2.1.7 on 2019-08-15 19:18

import catalogue.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0018_auto_20190815_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(max_length=10000, null=True)),
                ('title', models.CharField(max_length=10000, null=True)),
                ('project', models.CharField(choices=[('Insert tuples here', 'Insert tuples here')], default='--None--', max_length=99)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='case',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='user',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=catalogue.models.name_media_file, validators=[django.core.validators.FileExtensionValidator(('pdf', 'csv'))]),
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
