# Generated by Django 2.1.7 on 2019-08-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20190815_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Upload'),
        ),
    ]
