# Generated by Django 2.1.7 on 2019-08-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20190815_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='case',
            new_name='upload',
        ),
    ]
