# Generated by Django 2.1.7 on 2019-08-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20190816_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='user',
            new_name='user_id',
        ),
    ]
