# Generated by Django 2.1.7 on 2019-08-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20190816_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='user_id',
            new_name='user',
        ),
    ]
