# Generated by Django 2.1.7 on 2019-08-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20190816_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='author',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_disease',
        ),
        migrations.AlterField(
            model_name='upload',
            name='project',
            field=models.CharField(choices=[('Create New Project', 'Create New Project'), ('Use existing project', 'Use existing project')], default='--None--', max_length=99),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
